const CREATED = 201;
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const DOCUMENT_NOT_FOUND_ERROR = 404;
const ASSERTION_ERROR = 409;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  CREATED,
  BAD_REQUEST,
  UNAUTHORIZED,
  FORBIDDEN,
  DOCUMENT_NOT_FOUND_ERROR,
  INTERNAL_SERVER_ERROR,
  ASSERTION_ERROR,
};
