const CREATED = 201;
const BAD_REQUEST = 400;
const DOCUMENT_NOT_FOUND_ERROR = 404;
const INTERNAL_SERVER_ERROR = 500;
const UNAUTHORIZED = 401;
const ASSERTION_ERROR = 409;

module.exports = {
  CREATED,
  BAD_REQUEST,
  DOCUMENT_NOT_FOUND_ERROR,
  INTERNAL_SERVER_ERROR,
  UNAUTHORIZED,
  ASSERTION_ERROR,
};
